import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "Next.js Tutorial: Counter",
    default: "%s | Codevolution",
    absolute: "",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
